language: node_js
node_js:
  - "6.9.1"
install:
  - npm install yarn -g
  - yarn
sudo: required
services:
  - docker
cache:
  directories:
    - node_modules
script:
  - npm run test &&
    bash ./go.sh build
deploy:
  skip_cleanup: true
  provider: script
  script:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - bash ./go.sh push && bash scripts/deploy.sh
  on:
    all_branches: true
