FROM mysql:5.7

MAINTAINER madou <laheen@gmail.com>
LABEL Description="Database server for api.gw2armory.com"

# Exposes port 3306 to other containers (NOT the host) via. --link
# https://docs.docker.com/userguide/dockerlinks/
# https://docs.docker.com/reference/builder/
EXPOSE 3306
