FROM node:0.12.7

MAINTAINER madou <laheen@gmail.com>
LABEL Description="Development server container for api.armory.net.au"

WORKDIR /opt

COPY package.json /opt/package.json
RUN npm install

ENTRYPOINT ["gulp", "test:auto"]